#!/usr/bin/env bash
# Arguments: $APP $INTERNAL_PORT $INTERNAL_IP_ADDRESS
# Create a custom nginx.conf that enable the app to listen at port 80

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
PORT="$2"
INTERNAL_IP="$3"
EXTERNAL_IP="$(curl -s http://whatismijnip.nl |cut -d " " -f 5)"

template="upstream $APP-domains { server $INTERNAL_IP:$PORT; }
server {
  listen        [::]:80;
  listen        80;
  server_name   $EXTERNAL_IP;
  
  location / {
    proxy_pass http://$APP-domains; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
    proxy_cache_bypass \$http_upgrade;
  }
}
"

rm -f $DOKKU_ROOT/$APP/nginx.conf

echo '-----> Creating nginx.conf to redirect APP to external port 80'
echo "$template" > $DOKKU_ROOT/$APP/nginx.conf

echo '-----> Reloading nginx...'
sudo /etc/init.d/nginx reload > /dev/null

cat
